# Generated by Django 5.0.1 on 2025-05-02 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('urgence', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('resultats', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('liensUtiles', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('intensite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyses', models.ManyToManyField(related_name='historiques', to='diagnostic.analyse')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='analyse',
            name='symptomes',
            field=models.ManyToManyField(related_name='analyses', to='diagnostic.symptom'),
        ),
    ]
