services:
    react:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - /app/node_modules
    

    django:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"